title: Suleman's Portfolio - Building Kwen City
description: This portfolio showcases my Data Structures and Algorithms project: Kwen City, a visionary smart city model integrating advanced algorithms for optimized urban planning, resource management, and citizen services.
theme: jekyll-theme-cayman
